sonar.projectKey=kauan2872_projetoindividual-main
sonar.organization=kauan2872
sonar.projectName=mk.js
sonar.projectVersion=1.0.0

sonar.sources=server
sonar.exclusions=server/node_modules/**,server/coverage/**,server/tests/**
sonar.tests=server/tests

sonar.javascript.lcov.reportPaths=server/coverage/lcov.info
sonar.coverage.exclusions=server/tests/**

sonar.sourceEncoding=UTF-8
