apiVersion: v1
kind: Secret
metadata:
  name: mkjs-db-secret
  namespace: mkjs
type: Opaque
data:
  # echo -n 'mkjs' | base64
  POSTGRES_USER: bWtqcw==
  POSTGRES_PASSWORD: bWtqcw==
  POSTGRES_DB: bWtqc2Ri
