FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY . .

RUN addgroup -S mkjs && adduser -S mkjs -G mkjs
USER mkjs

EXPOSE 55555

CMD ["node", "server.js"]
